is it jsut me or are there more emo freaks out on the street now that that emo freak book came out 
its impossible to find vampire fangs at the costume store because everyone is trying to cosplay the self insert character in the one MCR fanfiction...
who the fuck is my chemical romance /
